### ISSUE TITLE
Text parts disappearing Пропадают куски текста.

### ISSUE THREAD

**Issue by Dreamer-4pda** [yanus171/Handy-News-Reader#124]
Если текст сделан ссылкой, то он может пропасть.
Пример статьи:
http://4pda.ru/2018/12/19/355138/
![Screenshot_20190221-070239__](https://user-images.githubusercontent.com/4630430/56482423-cbfd6c80-64cc-11e9-8e0d-5ed25603bcdd.png)
![Screenshot_20190221-070336_ForPDA](https://user-images.githubusercontent.com/4630430/56482424-cc960300-64cc-11e9-8dac-44be65ccc9bc.png)
![Screenshot_20190410-070346_ForPDA](https://user-images.githubusercontent.com/4630430/56482426-cd2e9980-64cc-11e9-80cf-c129a7d4c931.png)
![Screenshot_20190410-070317__](https://user-images.githubusercontent.com/4630430/56482427-cd2e9980-64cc-11e9-99a6-7493869291e8.png)

**Comment by yanus171** [comment]
Попробую поправить

**Comment by ThomasLeigh** [comment]
I've just noticed that some text piece is missing. The article: https://www.wired.com/story/blind-youtube-creators . The missing piece is placed within this fragment:

"He turned that frustrating experience into a YouTube channel: the Blind Film Critic." - this is "Blind Film Critic" (a hyperlink). In HNR it is displayed like that: "YouTube channel: the ." - and then the text goes on.

**Comment by yanus171** [comment]
This is because of clearing html content via several regex fond and remove (for example private static final Pattern REF_REPLY_PATTERN = Pattern.compile("<a[^>]+(reply|thread|comment|user)[^>]+(.)*?/a>", Pattern.CASE_INSENSITIVE);
 in file https://github.com/yanus171/Flym/blob/master/FlymFork/src/main/java/ru/yanus171/feedexfork/utils/HtmlUtils.java  So I don't know what to do. I can make a setting not to clear content, global or peer feed, or even give a user ability to define custom regexes for clearing, but it's to complex and there should be more elegant solution
