### ISSUE TITLE
"autoload images" works only together with "load full article"

### ISSUE THREAD

**Issue by bcm314** [yanus171/Handy-News-Reader#128]
"autoload images" seems not working (also a German reviewer wrote so and gave only 1 star)
I figured out, it works only if "load full article" is set (or did I miss anything?).

I suggest: in the options, ONLY if "load full article" is set, enable/show the option about "autoload images".

or an other way: if you set "autoload images", also "load full article" will be set automatically. And when deselecting the later, also deselect the first.

**Comment by yanus171** [comment]
1. To load images in auto refresh, go to feed settings and check Auto load images.
2. Images are loaded only in refresh session when corresponding articles were added (only for the new articles). Find images are placed in tasks quenue to download. If the refresh process was canceled (by user or by app due to absence of the internet connection for example) the images from task quenue will be downloaded in the next refresh. If refresh is canceled by user the test quenue is cleared and images that were in quenue will not be auto downloaded. They will be downloaded only when article would be opened for reading.

**Comment by yanus171** [comment]
And load full text setting is independent from images auto load

**Comment by Ryuno-Ki** [comment]
Thanks for clarification.
I was wondering, how to triggera download of the ~4k images, which are hogging in my queue...

**Comment by yanus171** [comment]
Set max image size pref

**Comment by Ryuno-Ki** [comment]
It is. Adjusted from 2048 to 1024.
The queue filled up due to OOM crashes (and OS killing the app).

However, I don't want to hijack this thread.

**Comment by yanus171** [comment]
How do you understand that quenue is filled up?

You should increase the max size to load miter images.

What do you mean by hijack this thread?

**Comment by Ryuno-Ki** [comment]
> How do you understand that quenue is filled up?

When I load (IIRC a single feed), and it finishes mobilizing, I can see article images being loaded. Not only of those of the feed, but where it left off.

> You should increase the max size to load miter images.

Just to avoid confusion: Where?

> What do you mean by hijack this thread?

I'm not the OP. Chances are, that my issue has different causes.
