### ISSUE TITLE
"Show original text on article list" - wrong order

### ISSUE THREAD

**Issue by bcm314** [yanus171/Handy-News-Reader#134]
For one feed I've set the option "Show original text on article list".
The "Articles order" is not the same as all others. I would also prefer display newest first.

**Comment by yanus171** [comment]
And I use it for rss of forums and prefer to see newest last... So we need a preference... This is not ease to implement, because there is auto mark as read in on this mode (while you scroll items). And that algorithm is made only for one direction now. So it should be updated also. This issue may be resolved together with #94 and #64 and #57

**Comment by bcm314** [comment]
When having a lot of (also read) articles, you need a long, long time to scroll down till the end.

But today, I've discovered an interesting thing:
when there is (at least) one unread article, it will be scrolled to the oldest unread one.

So an other idea: if there is not any unread article, display the newest read one.
