### ISSUE TITLE
A hyperlink-(distraction)-free 'Zen Mode'.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#227]
There are some people who would highly appreciate a plain, clean reading experience, i.e. without any distractions, including hyperlinks. So You could add an option to disable hyperlinks if one wishes so. As a result hyperlinks would be indistinguishable from all the rest of the text. And You could call this feature "Zen Mode" :) .

@SIRSteiner , @Ryuno-Ki  , @Spleeeno , @paulle - could You please share Your take on this one? :

**Comment by SIRSteiner** [comment]
If some people want it, okay. I don't need this feature. But I don't know what "Zen mode" means. I would prefer "Disable hyperlinks".

**Comment by ThomasLeigh** [comment]
I saw _"Zen Mode"_ within several apps, it consists of disabling various things to minimize distractions while using the app. It is often called this way. Of course I also prefer _"Disable hyperlinks"_, I'd love to see the feature called _"Zen Mode"_ - and its description _"Disable hyperlinks"_.

**Comment by SIRSteiner** [comment]
Zen mode at OnePlus smartphone means that you can use it only with many restrictions for 20 minutes. That would confuse me. But if it is usual in english language then you can name it so.

**Comment by ThomasLeigh** [comment]
There is no strict meaning to this phrase, but the sole guideline to make something more distraction-free, cleaner, more focus-oriented. Some apps, for example, use _"Zen Mode"_ to simplify the interface as much as possible, downsizing it to its very core.

**Comment by Spleeeno** [comment]
I'm not sure if this makes sense as a global setting, but maybe in the feed settings?
I've seen some feeds where basically everything is a link and disabling the distinction/on-click-function would be pretty zen for those. But I guess most of those can be fixed by enabling the full-text option.

IMHO just giving me a setting to set the hyperlink color to the default fontcolor while keeping the underline would make more sense. With an "absolute zen mode" (no fontcolor,  underline or link functionality) I might end up with some articles not making sense, even though they left links to more detailed explanations - I just didnt realize it, cause they look like normal text on that mode...

**Comment by ThomasLeigh** [comment]
@Spleeeno Thank You for Your in-depth input.

>With an "absolute zen mode" (...) I might end up with some articles not making sense,

This is why _"Zen Mode"_ is not good for every article - like meditation is not good for every possible environment. It could be used whenever possible. But You've made this inspirational point:

>set the hyperlink color to the default font color

Thanks to You I realize that it is possible now, although (and unfortunately) by hand. Still, it would be nice to have a dedicated option (a checkbox) for that in settings.

**Comment by Spleeeno** [comment]
Oh yeah, just realized the hyperlink fg/bg settings are now in the latest build.
Nice work @yanus171

**Comment by Ryuno-Ki** [comment]
Since you askedfor my opinion...
I wouldn't have much value for this.
However, if you remove the links, add some `[0]` behind it (number increasing) and list those at the end of the article.

This way, I could see the link if I happen to find it interesting.
