### ISSUE TITLE
A notification on long inactive feeds.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#272]
I think it's easy to miss that some of our subscribed feeds may be currently inactive/broken. **What do You think on *HNR* lets You know when some time-span of a feed inactivity has been reached?** Something like a pop-up window with the message:

> "It seems that *"The Name Of a Feed"* hasn't provided any new article for a long time now. Would You like to remove it from Your subscriptions?"

buttons: *"Yes."*, *"No, thank You."*.

**Comment by Ryuno-Ki** [comment]
I'm currently work around it by putting the feed URLs on my website and let a script fetch them.
This way, it will display the date, so I can tell from my website, when the last update of a feed was.
But yeah, some kind of ability to query for outdated blogs (e.g. because the URL changed) would be nice.
