### ISSUE TITLE
Heading of "Global filter..." is not correct

### ISSUE THREAD

**Issue by SIRSteiner** [yanus171/Handy-News-Reader#31]
![screenshot_20181227-133038](https://user-images.githubusercontent.com/3488638/50480484-79a7b580-09dc-11e9-802e-1b7051893ac9.png)

Please look at the red selection. Thank you

**Comment by SIRSteiner** [comment]
Sorry, I had not understood that feature. This is not a filter this is an option to add favorites automatically. The english string confused me. I will change the german translation to the right meaning.

**Comment by SIRSteiner** [comment]
So we can close this issue....

**Comment by SIRSteiner** [comment]
In general I replaced all "starred" things with "favorite(s)" in german translation. Maybe this section should be called "Auto favorites..." because in my opinion "filter" means accept and reject like filters in a single feed. But I am not an expert in engish language.
@ThomasLeigh: What do you think?

**Comment by ThomasLeigh** [comment]
_"I replaced all "starred" things with "favorite(s)" in german translation. Maybe this section should be called "Auto favorites..." because in my opinion "filter" means accept and reject like filters in a single feed. (...)
@ThomasLeigh: What do you think?"_

I think it is a good idea because it simplifies the thing. I agree that _"Auto Favorites"_ would be also a good choice (instead of _"Global Filter"_).

However, I'd love to have it all changed in a following way:

- **"Read It Later"** instead of "Starred" and "Favorites",
- **"Important Articles"** instead of "Mark(ed) as starred" in current Global Filter (which in this case would be named as **_"Notify on Important Articles"_**);

I'm dreaming about it! :)

See more explanation on those two in here: https://handynewsreader.blogspot.com -  the "upcoming" section.

**Comment by ThomasLeigh** [comment]
BTW, _@SIRSteiner_ , I'd like to reach You by e-mail to propose something **regarding German language,** may I? Or please visit https://handynewsreader.blogspot.com , the _contact_ item in menu.

**Comment by SIRSteiner** [comment]
I sent you an e-mail...

**Comment by yanus171** [comment]
I, no! Now there are two of them now! :)

**Comment by yanus171** [comment]
> "Read It Later" instead of "Starred" and "Favorites",
I often star an article which is interesting for ME and I don't want it to disappear after old period. But I don't want to Read it LATER. I want to read it right NOW.

**Comment by yanus171** [comment]
And Read later also refers to loading external link

**Comment by SIRSteiner** [comment]
For me "Favorite" is intuitive enough. "Read it later" would also confuse me because a "starred" article can be marked as "read".

"Saved articles" would also be a good choice in my opinion because it describes this feature  good.

But I don't think we need another category for nearly the same feature.

**Comment by ThomasLeigh** [comment]
_""Read it later" would also confuse me because a "starred" article can be marked as "read"."_

This is the reason it should be changed to _"Viewed"_ or _"Displayed"_ - instead of _"read"_.


_"But I don't think we need another category for nearly the same feature."_

The point is this is not the same feature. Of course it may be put in one place - regardless of user's intention (to read it later or just to preserve) - in this case _"favorites"_ seems to be all right.

But in My opinion it could be arranged in a much better way. As an average user **I don't know what for "favorites" are.** I do know, however, what _"read it later"_ or _"saved"_ could be for. In other words I'd choose a way in which a user don't need to think how those _"favorites"_ could be handy for him or her. **I am a strong believer in a manner in which an app is so intuitive that I don't need to think or wonder about it - just use.** This way many more users can benefit from the app - not only the ones who had the idea how it could be used well.

**Comment by SIRSteiner** [comment]
I understand - "Favorites" is not the best choice. But with "Saved articles" you don't have to think about read later or not and read or unread. Why do we need another "Read it later"? It is clearly understandable that "Saved articles" can be read all the time - now and later. I know it's not the same but sometimes less is more...

**Comment by ThomasLeigh** [comment]
_"But with "Saved articles" you don't have to think about read later or not and read or unread. Why do we need another "Read it later""_

For the same reason as before: because it is not clear/precise enough. Not everyone will think about "saved" articles as a way of preserving them to read later.

Having both sections at hand will assure You that the app will meet **and discover** _everybody's_ needs. The same theme is in a case of _"Global Filter"_ - some of us will see that this feature could be of great help, letting us know every time an important article pops up. But if we could name it _"Notify on Important Articles"_ - I am sure that it could be clear for many more users how this particular feature could benefit them.

_"sometimes less is more..."_

One way or another - if it will be one section instead of two, there is always be a semantic confusion, because none of those two features are precise enough.

**There may be clever users out there. But what if the app itself will be clever? :)**
