### ISSUE TITLE
error feed

### ISSUE THREAD

**Issue by fenix-soft** [yanus171/Handy-News-Reader#403]
I have an error when the program tries to load this feed
https://www.galluraoggi.it/feed/

the error is as follows in the screenshot
https://images2.imgbox.com/4f/d4/zu5xtxKj_o.png

![nome_immagine](https://images2.imgbox.com/4f/d4/zu5xtxKj_o.png) 

the feed in other pc programs like quite rrs does not give an error and the program reads the feeds calmly; with Handy-News-Reader there is an error ...

I use Android Oreo

can you help me? thank you

**Comment by yanus171** [comment]
Try [810](https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1203085115)

**Comment by ArtexJay** [comment]
> Try [810](https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1203085115)


Still doesn't seem to be working
An error is presented as seen in the screenshot below when you refresh the feed, this issue was not present in  v0.17.1 (PlayStore Stable build) 
Edit: I tried builds v0.17.7 and v0.17.11 both of which have this error too.


![Screenshot_2022-09-28-04-03-57-132_ru yanus171 feedexfork1](https://user-images.githubusercontent.com/32932497/192725031-b2fb4406-5619-452c-91f1-d8db14e9f05e.jpg)

New Feed erroring: https://tass.com/rss/v2.xml

**Comment by yanus171** [comment]
Try Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1261320390

**Comment by yanus171** [comment]
Test different feeds please
