### ISSUE TITLE
Various questions.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#411]
I am in the process of writing HNR FAQ. As I realize that various questions pop up down the road, I’ve decided to dedicate this place to this purpose, i.e., to ask various HNR-related questions in the matters too small to create separate threads.

My first questions out of my head:

1. “Download all images button (link) in article text (near Download next N images)” - this is a little confusing for me because I can’t find “Download next N images” as well as “Download all images” button... Could You please point out where exactly I can find those two elements?

2. “Display the count of images and texts, scheduled to load on the next refresh ” - how the app knows how many images and texts are out there to be loaded - before I start the refresh? Or maybe it refers to the very moment just after initiating the refresh, but still during the process?

3. If I have set entries kept time as a few days - what will happen with an article placed within Favorites after those few days? And, on the other hand, what will happen with an article places within ‘Read Later’?

**Comment by yanus171** [comment]
1. There is a link with text in English language: Download the image, Next 
10, All. It's hard to find because it's occurs only after the last auto 
loaded article image (corresponding to Max image download count)

2. After parsing new articles (RSS or full version) the app adds to talk 
list the images item is need to load (again corresponding to Max image 
download count). Often during auto refresh system do not gives the app 
enough time to finish the refresh progress completely (for battery saving 
purposes). So some images remains in task list and would be loaded after 
next refresh. There is also a situation when image can't be loaded due to 
weak internet connection or server side problems in this case the images 
remains in task list for the next refresh process (there are three attempts 
for every image before it would be deleted for task list). So the image 
count in task list is displayed there with prefix I. The task list also 
contains the full texts scheduled to download - this count is displayed 
with prefix T.

3. Favourites are never deleted automatically even during Delete all 
operation in article list screen. Read it later articles auto deleted as in 
other feeds.

This is a great idea to create the FAQ. But may be IST worth's to add 
separate issues, and create for them new label: FAQ?

**Comment by ThomasLeigh** [comment]
> This is a great idea to create the FAQ. But may be IST worth's to add
separate issues, and create for them new label: FAQ?

If a bunch of new threads don’t bother You, I like this idea :)

**Comment by yanus171** [comment]
That's ok.

**Comment by ThomasLeigh** [comment]
@yanus171 
> the count of images and texts, scheduled to load on the next refresh

Where exactly this count is displayed?

**Comment by yanus171** [comment]
In All articles item of feed selector


Thomas Leigh <notifications@github.com> 6 апреля 2020 г. 21:23:19 написал:

> @yanus171
>> the count of images and texts, scheduled to load on the next refresh
>
> Where exactly this count is displayed?

**Comment by ThomasLeigh** [comment]
> In All articles item of feed selector

You  mean on the sidebar, where many categories have a number (e.g., 22 M) placed under them?

**Comment by yanus171** [comment]
No, that number is the space that that feed/group images occupy on the 
phone storage.


Thomas Leigh <notifications@github.com> 7 апреля 2020 г. 17:50:05 написал:

**Comment by yanus171** [comment]
![Screenshot_20200407-191733](https://user-images.githubusercontent.com/18382136/78694524-743a5a00-7905-11ea-82a2-13340af4aa3e.jpg)
See thr text "To load:"

**Comment by ThomasLeigh** [comment]
Oh, I see... is it displayed only under “All articles”?

**Comment by yanus171** [comment]
Yes only under all articles. It's the sum from all feeds
