### ISSUE TITLE
When exactly “Article reading notification” is displayed?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#465]
...

**Comment by yanus171** [comment]
When you reading an article.

**Comment by ThomasLeigh** [comment]
I’m not sure I understand the purpose of this feature. Could You please explain in details why it is a good idea? My first thought was that it is for the app to work 100% properly by not being killed by the OS - because this would prevent the app from performing feeds refresh operation on time. But now You say that it is supposed to work regarding reading articles. If I’m reading an article, I usually have the article always displayed on the screen. If not, You’ve recently introduced a desktop shortcut to the currently read article. So... I’m a little confused.

**Comment by yanus171** [comment]
Refresh operation is not interrupted by system because of notification down during it. 

When you read an article and then switch to other app for some time (on my phone this can be a minute) the system may decide to free up memory and kill the app. So when you would return to HNR it should create article screen from the beginning and restore last reading position (I had made much efforts to make that work properly). In the case of long article it can consume noticeable time.

But if the app shows persistent notification, it says to system that the app is valuable for user and should not be killed by the system. So in this case the switching to HNR from other app would be very quick.

**Comment by ThomasLeigh** [comment]
**Thank You so much for the detailed description of the feature.**

> Refresh operation is not interrupted by system because of notification shown during it.

But sometimes I had the impression that the app is not allowed by the OS to refresh while I haven’t been using my phone for a longer time.

**Comment by yanus171** [comment]
After screen was turned off the phone goes to Doze mode (google for it), so 
the more time the phone screen is turned off the rare it wakes up for 
background tasks (feeds refresh is one of them) execution.

Also there is no guarantee that when screen is off the refresh process 
would have time to complete in time period provided for it by system. And 
some full text or images would be queued for next refresh. Current queue 
info was added in one of the last app releases in feeds list All item (To 
load).

**Comment by ThomasLeigh** [comment]
Could we battle the Doze Mode with a similar persistent notification method applied not only for article reading, but always?

**Comment by yanus171** [comment]
Three persistent notification in HNR stores the app in memory, that can require from 100 to 200 Mb. This is significant. And I think it should be in case of article reading only.
