### ISSUE TITLE
Mark Read on Scroll

### ISSUE THREAD

**Issue by ghost** [yanus171/Handy-News-Reader#57]
I'd like the option to automatically mark articles as read when scrolling past them on the list. 

Basically the same thing gReader does.

**Comment by yanus171** [comment]
The app already has such a feature when a
in feed settings Show article text checkbox is checked.

**Comment by Riotous** [comment]
@yanus171 That's not what I'm describing. I'm not talking about having a checkbox on each article in the list, I'm talking about when you scroll past an article in the list, the action of scrolling past an article marks articles as read. In other words, when scrolling, all the articles that are no longer in view at the top when scrolling, get marked as read. 

gReader does this. See pic below in the middle of the image. 

![rss-feed-reader-greader](https://user-images.githubusercontent.com/42202207/52372540-4ad62380-2a0d-11e9-9cb8-e046969771a1.jpg)

**Comment by yanus171** [comment]
Make a long tap on the feed item in feed list (left moving panel), in feed settings check "Show original text on article list" checkbox, press back and see what happens

**Comment by Riotous** [comment]
@yanus171 That's not what I'm talking about, though.  I don't want the original text in the article list. I want the article list to continue to just be a list, and when I scroll past items on that list, I want them to  automatically get marked as read because I didn't want to read them, which is why I scrolled past them.

Marking items read as I scroll past them is another way to say "I don't want to read this and I don't want it showing up again, so mark it as read so it doesn't show up again".

**Comment by yanus171** [comment]
OK. Now I have understood you. And should this option be global or peer feed?

**Comment by Riotous** [comment]
@yanus171 Global. Thanks for considering my request. Sorry if I wasn't clear enough.

**Comment by yanus171** [comment]
And you didn't answer my question: Should this option be global or peer feed?

**Comment by Riotous** [comment]
@yanus171 I definitely said global in my response. Read it again?
