### ISSUE TITLE
Article text flashing.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#585]
While I browse articles the text often flashes. I’m not sure whether the source of this behavior is in the device or somewhere else. It looks [like that](https://cloud.trailofthelight.xyz/wl/?id=w3BIcq6LeeZbM7pxgRb42cpHXFyTHARx) - You can see the subtle flashing which occurs not always. Could something be done not to allow this flashing to happen?

**Comment by yanus171** [comment]
This is because article text is loaded only after the article was swiped. This was madde for the sake of perfomance. Imageine the case when you have opened afticle for reading, but lef or right (next\pervious) one is very big - so instead of reading your article you have to wait until left|right article would load
