### ISSUE TITLE
Why “feedex”, why “yanus”?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#595]
I am curious of those words origin, could You shed light on that? :)

**Comment by Ryuno-Ki** [comment]
I could imagine, it's [reverse domain name notation](https://en.wikipedia.org/wiki/Reverse_domain_name_notation) as I saw often in Java packages.

**Comment by yanus171** [comment]
Where do you read these words?

**Comment by ThomasLeigh** [comment]
Within the folder’s name where _HNR_ is stored:

`“ru.yanus171.feedexfork”`

It does look like a reverse DNS, but I am curious to know why those exact words, like, for example, nicknames etymology.

**Comment by yanus171** [comment]
The app folder name (when that app was setup to use external sdcard) 
contains unique package identifier for Android app. This is the only 
possible path the app can write files due to the Android system security 
demands.

Feedex is the package part that was in Flym to indicate that the project 
was firstly forked. yanus171 is my nickname

**Comment by ThomasLeigh** [comment]
> Feedex is the package part that was in Flym to indicate that the project
was firstly forked.

How does it indicate that?

> yanus171 is my nickname

Would You be willing to uncover why did You take such a nickname?
