### ISSUE TITLE
Please improve performance when showing group unread number 

### ISSUE THREAD

**Issue by XilinJia** [yanus171/Handy-News-Reader#604]
I noticed in settings that showing group unread numbers affect performance.  I turned it on, and indeed, performance goes way down.  Not sure what's going on inside the code (I can't imagine why just adding a few numbers would cause such big performance impact), but showing group unread numbers is important.  All my feeds are grouped into categories.  Without unread numbers on each group it's hard to select which group to read.

**Comment by yanus171** [comment]
Performance is defined by sqlite group query for updating left drawable info.
I could improve the performance by calculating these numbers once during 
periodical Delete old articles operation. But in that case this information 
would be updated not in real time.

**Comment by LeoK987** [comment]
The unread numbers are already available for every feed.  Why can't you add those up to get the unread number for a group?

**Comment by nikhilCad** [comment]
Yes @yanus171 why can't you just add the numbers up?

**Comment by yanus171** [comment]
Because the articles are stored in the database. So I need a SQL query to 
get the group numbers. In the case of hundreds and thousands total articles 
the execution of such a query would take a long time. (Sqlite in Android is 
highly restricted for memory consumption). And to keep the numbers actual 
such a query should be executed very often - in case of any operation 
(change current feed, read, star article, refresh etc).

The solution is to calculate the numbers not using the database. But in 
such a case I need to organise a mechanism of storing all articles info in 
memory and updating it. Implementing it would take a lot of time.

Generally the database is the most common case of lags in the app and such 
a mechanism would significantly improve the performance. May be some time I 
will have time to implement it...

**Comment by Ryuno-Ki** [comment]
> The solution is to calculate the numbers not using the database.

Wouldn't it be possible to have paginated queries (like, querying the articles of the first 25 feeds, then the next 25 ones and so on) and update the group unread number gradually?
(Instead of one big query, multiple smaller ones).

Or is the connection to the database the issue?
