### ISSUE TITLE
Add black theme (The backgroung is black | The words are white)

### ISSUE THREAD

**Issue by RAMAR-RAR** [yanus171/Handy-News-Reader#62]
-Add black theme (The backgroung is black | The words are white)

**Comment by yanus171** [comment]
What is the difference from current black theme?

**Comment by ThomasLeigh** [comment]
I suppose it may regard so-called _"AMOLED blackness"_, real black color (the current black theme is based on dark gray). But please, let the current dark theme be still available, because it is more eye-friendly in terms of contrast.

**Comment by meelten** [comment]
I second to that. Black theme would be really appreciated.

**Comment by Ryuno-Ki** [comment]
Note, that [white-on-black](https://contrast-ratio.com/#White-on-Black) is not the only high contrast (ratio of 21). [Yellow-onBlack](https://contrast-ratio.com/#yellow-on-Black) is quite high also (19.55).

However, according to [colour theory](http://www.writer2001.com/colwebcontrast.htm), this isn't the best option.
Consider using some less jarring examples.

Try also fullscreen background colour vs. partly background, since the effect is different.

**Comment by meelten** [comment]
The point is energy saving in devices with AMOLED displays: https://www.androidauthority.com/black-amoled-display-power-saving-541984/

**Comment by yanus171** [comment]
OK, I am not against black theme, but there is need to make significant changes in app since the checkbox would not suite to us to select theme.

Also this issue should be implemented with to set the colors manually

**Comment by meelten** [comment]
Sure, if you want add full color customization that would be possibly best option.

**Comment by yanus171** [comment]
See https://github.com/yanus171/Flym/releases/tag/v0.8.2

**Comment by Ryuno-Ki** [comment]
Related: https://medium.com/lookup-design/designing-a-dark-theme-for-oled-iphones-e13cdfea7ffe

**Comment by yanus171** [comment]
You can now set black background manualy in app settings
