### ISSUE TITLE
full text not fetched: gets an eperm error

### ISSUE THREAD

**Issue by amit3s** [yanus171/Handy-News-Reader#702]
Hello,

After updating to 0.16.7, full text downloads do not happen. In the article list view while the fetch is in progress, an error message shows up in red at the bottom with filenames that can't be opened due to EPERM.

**Comment by yanus171** [comment]
You should change the storage setting to cache or as card. This is the 
price for Google play update

**Comment by amit3s** [comment]
I don't get the point about the google play update, since I do not have play services installed - I just run lineageos, and get the app via fdroid.

But I updated storage, and do not see this anymore, thanks!

**Comment by AlexandreBonneau** [comment]
I had the same problem for months, since the default `/emulated/0` path was selected.
Perhaps the app could detected if such a faulty path is used from 'old' installs, and display a warning for the users?

Anyway, thanks for the tip @yanus171, using either the cache or data storage option was the way to go to fix this annoying bug!
